from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_PreciousList.html
# flake8: noqa
blueprints_data: list[Data] = [
Data("FILE-M0101SA - Archetype Sword", valid=False),
Data("FILE-M0102GG - Archetype Slair II", valid=False),
Data("FILE-M0103SA - Archetype Sword II", valid=False),
Data("FILE-M0201SA - Archetype Blades", valid=False),
Data("FILE-M0202GG - Archetype Ralzes", valid=False),
Data("FILE-M0203SA - Archetype Blades II", valid=False),
Data("FILE-M0301SA - Archetype Knife III", valid=False),
Data("FILE-M0302GG - Archetype Riv", valid=False),
Data("FILE-M0303SA - Archetype Knife II", valid=False),
Data("FILE-M0401GG - Archetype Paive", valid=False),
Data("FILE-M0402SA - Archetype Shield", valid=False),
Data("FILE-M0403GG - Advanced Archetype Paive", valid=False),
Data("FILE-M0501SA - Archetype Spear", valid=False),
Data("FILE-M0502GG - Archetype Parce", valid=False),
Data("FILE-M0503SA - Archetype Spear II", valid=False),
Data("FILE-M0601GG - Archetype Fulge", valid=False),
Data("FILE-M0602SA - Archetype Saber", valid=False),
Data("FILE-M0603GG - Archetype Fulge II", valid=False),
Data("FILE-R0101SA - Archetype Assault Rifle III", valid=False),
Data("FILE-R0102GG - Archetype Avagar", valid=False),
Data("FILE-R0103SA - Archetype Assault Rifle II", valid=False),
Data("FILE-R0201SA - Archetype Dual Guns", valid=False),
Data("FILE-R0202GG - Archetype Gemels", valid=False),
Data("FILE-R0203SA - Archetype Dual Guns II", valid=False),
Data("FILE-R0301GG - Archetype Lastyr II", valid=False),
Data("FILE-R0302SA - Archetype Raygun", valid=False),
Data("FILE-R0303GG - Archetype Lastyr III", valid=False),
Data("FILE-R0401SA - Archetype Machine", valid=False),
Data("FILE-R0402GG - Archetype Repethe", valid=False),
Data("FILE-R0403SA - Archetype Machine II", valid=False),
Data("FILE-R0501SA - Archetype Sniper Rifle", valid=False),
Data("FILE-R0502GG - Archetype Retic", valid=False),
Data("FILE-R0503SA - Archetype Sniper Rifle II", valid=False),
Data("FILE-R0601GG - Archetype Psylans", valid=False),
Data("FILE-R0602SA - Archetype Launchers", valid=False),
Data("FILE-R0603GG - Advanced Archetype Psylans", valid=False),
Data("FILE-M0101SS - Masterstroke Glaive"),
Data("FILE-M0102SS - Masterstroke Glaive II"),
Data("FILE-M0201CC - Original Twins"),
Data("FILE-M0202OR - Original Watxes"),
Data("FILE-M0203SS - Masterstroke Edges II"),
Data("FILE-M0204SS - Masterstroke Edges"),
Data("FILE-M0301NP - Original Pokepoke"),
Data("FILE-M0302OR - Original Iyst"),
Data("FILE-M0303OR - Original Iyst II"),
Data("FILE-M0401CC - Original Haven"),
Data("FILE-M0402CC - Original Haven II"),
Data("FILE-M0403NP - Original Thudclang"),
Data("FILE-M0501CC - Original Bolide"),
Data("FILE-M0502OR - Original Jyth"),
Data("FILE-M0503SS - Masterstroke Lance"),
Data("FILE-M0601SS - Masterstroke Lightblade"),
Data("FILE-M0602SS - Masterstroke Lightblade II"),
Data("FILE-R0101CC - Original Assailer"),
Data("FILE-R0102SS - Masterstroke Raidrifle"),
Data("FILE-R0201CC - Original Dyads"),
Data("FILE-R0202CC - Original Dyads III"),
Data("FILE-R0203CC - Original Dyads II"),
Data("FILE-R0204NP - Original Bangbangs"),
Data("FILE-R0205SS - Masterstroke Sidearm"),
Data("FILE-R0301CC - Original Strobe"),
Data("FILE-R0401CC - Original Crank"),
Data("FILE-R0402NP - Original Ratatatta"),
Data("FILE-R0403OR - Original Ziyse"),
Data("FILE-R0501CC - Original Trigger"),
Data("FILE-R0502NP - Original Thwipper"),
Data("FILE-R0503SS - Masterstroke Deadsight"),
Data("FILE-R0504SS - Masterstroke Deadsight II"),
Data("FILE-R0601CC - Original Saboteurs"),
Data("FILE-R0602NP - Original Fwooshers"),
Data("FILE-R0603OR - Original Zorcyses"),
Data("FILE-LM0101SA - 3276", valid=False),
Data("FILE-LM0102SA - 3277", valid=False),
Data("FILE-LM0103SA - 3278", valid=False),
Data("FILE-LM0104SA - 3279", valid=False),
Data("FILE-LM0105SA - 3280", valid=False),
Data("FILE-LM0106SA - 3281", valid=False),
Data("FILE-GEAR01SS-BD - Six Stars Ritual Bodywear", valid=False),
Data("FILE-GEAR01SS-RA - Six Stars Ritual Band R", valid=False),
Data("FILE-GEAR01SS-LA - Six Stars Ritual Band L", valid=False),
Data("FILE-GEAR01SS-LG - Six Stars Ritual Legwear", valid=False),
Data("FILE-GEAR02FC-BD - Supercivilization Attire", valid=False),
Data("FILE-GEAR03FC-BD - Elite Supercivilization Attire", valid=False),
Data("FILE-GEAR04CC-HD - Black Bunnyband", valid=False),
Data("FILE-GEAR05CC-HD - Red Bunnyband", valid=False),
Data("FILE-GEAR06CC-HD - White Bunnyband", valid=False),
Data("FILE-GEAR07CC-BD - Bunnytop", valid=False),
Data("FILE-GEAR07CC-RA - Bunnycuff R", valid=False),
Data("FILE-GEAR07CC-LA - Bunnycuff L", valid=False),
Data("FILE-GEAR07CC-LG - Bunnyhoppers", valid=False),
Data("FILE-GEAR12CC-BD - Bunnybod", valid=False),
Data("FILE-GEAR12CC-RA - Bunnylink R", valid=False),
Data("FILE-GEAR12CC-LA - Bunnylink L", valid=False),
Data("FILE-GEAR08GG-HD - Reginal Comm"),
Data("FILE-GEAR08GG-BD - Reginal Plastron"),
Data("FILE-GEAR08GG-RA - Reginal Bangle R"),
Data("FILE-GEAR08GG-LA - Reginal Bangle L"),
Data("FILE-GEAR08GG-LG - Reginal Cords"),
Data("FILE-GEAR09GG-HD - Regal Comm"),
Data("FILE-GEAR09GG-BD - Regal Plastron"),
Data("FILE-GEAR09GG-RA - Regal Bangle R"),
Data("FILE-GEAR09GG-LA - Regal Bangle L"),
Data("FILE-GEAR09GG-LG - Regal Cords"),
Data("FILE-GEAR10GG-HD - Infinite Comm"),
Data("FILE-GEAR10GG-BD - Infinite Plastron"),
Data("FILE-GEAR10GG-RA - Infinite Bangle R"),
Data("FILE-GEAR10GG-LA - Infinite Bangle L"),
Data("FILE-GEAR10GG-LG - Infinite Cords"),
Data("FILE-GEAR11GG-HD - True Comm"),
Data("FILE-GEAR11GG-BD - True Plastron"),
Data("FILE-GEAR11GG-RA - True Bangle R"),
Data("FILE-GEAR11GG-LA - True Bangle L"),
Data("FILE-GEAR11GG-LG - True Cords"),
Data("FILE-USP0140SA - SRM-USP140SA Hexad-Partican"),
Data("FILE-USP0160SA - SRM-USP160SA Hexad-Partican"),
Data("FILE-USP0180SA - SRM-USP180SA Hexad-Partican"),
Data("FILE-USP0240SA - SRM-USP240SA Zenith-Cannon"),
Data("FILE-USP0260SA - SRM-USP260SA Zenith-Cannon"),
Data("FILE-USP0280SA - SRM-USP280SA Zenith-Cannon"),
Data("FILE-USP0340GG - SRM-USP340GG Zweihand-Q"),
Data("FILE-USP0360GG - SRM-USP360GG Zweihand-Q"),
Data("FILE-USP0380GG - SRM-USP380GG Zweihand-Q"),
Data("FILE-USP0440ME - SRM-USP440ME Trident-Anchor"),
Data("FILE-USP0460ME - SRM-USP460ME Trident-Anchor"),
Data("FILE-USP0480ME - SRM-USP480ME Trident-Anchor"),
Data("FILE-USP0540GG - SSM-USP540GG Electric-Flood"),
Data("FILE-USP0560GG - SSM-USP560GG Electric-Flood"),
Data("FILE-USP0580GG - SSM-USP580GG Electric-Flood"),
Data("FILE-USP0640ME - SSM-USP640ME Voltaic-Tusk"),
Data("FILE-USP0660ME - SSM-USP660ME Voltaic-Tusk"),
Data("FILE-USP0680ME - SSM-USP680ME Voltaic-Tusk"),
Data("FILE-USP0740SA - SRM-USP740SA Antimatter-R"),
Data("FILE-USP0760SA - SRM-USP760SA Antimatter-R"),
Data("FILE-USP0780SA - SRM-USP780SA Antimatter-R"),
Data("FILE-USP0840SA - SRM-USP840SA G-Piledriver"),
Data("FILE-USP0860SA - SRM-USP860SA G-Piledriver"),
Data("FILE-USP0880SA - SRM-USP880SA G-Piledriver"),
Data("FILE-USP0940GG - SRM-USP940GG Dragoon-Lance"),
Data("FILE-USP0960GG - SRM-USP960GG Dragoon-Lance"),
Data("FILE-USP0980GG - SRM-USP980GG Dragoon-Lance"),
Data("FILE-USP1040GG - SRM-USP1040GG Drone-Storm"),
Data("FILE-USP1060GG - SRM-USP1060GG Drone-Storm"),
Data("FILE-USP1080GG - SRM-USP1080GG Drone-Storm"),
Data("FILE-USP1140SA - SSM-USP1140SA Deus-Crusher"),
Data("FILE-USP1160SA - SSM-USP1160SA Deus-Crusher"),
Data("FILE-USP1180SA - SSM-USP1180SA Deus-Crusher"),
Data("FILE-USP1240ME - SSM-USP1240ME Barrage-Cloak"),
Data("FILE-USP1260ME - SSM-USP1260ME Barrage-Cloak"),
Data("FILE-USP1280ME - SSM-USP1280ME Barrage-Cloak"),
Data("FILE-USP1340SA - SRM-USP1340SA Detonation-F"),
Data("FILE-USP1360SA - SRM-USP1360SA Detonation-F"),
Data("FILE-USP1380SA - SRM-USP1380SA Detonation-F"),
Data("FILE-USP1440SA - SSM-USP1440SA Megaflame-B"),
Data("FILE-USP1460SA - SSM-USP1460SA Megaflame-B"),
Data("FILE-USP1480SA - SSM-USP1480SA Megaflame-B"),
Data("UNUSED - 91", valid=False),
Data("FILE-SK-FORMULA80"),
Data("UNUSED - 118", valid=False),
Data("FILE-SK-URBAN80"),
Data("UNUSED - 152", valid=False),
Data("FILE-SK-VERUS80"),
Data("UNUSED - 186", valid=False),
Data("FILE-SK-LAILAH80"),
Data("UNUSED - 220", valid=False),
Data("FILE-SK-INFERNO80"),
Data("UNUSED - 251", valid=False),
Data("FILE-SK-MASTEMA80"),
Data("UNUSED - 282", valid=False),
Data("FILE-SK-AMDUSIAS80"),
Data("UNUSED - 284", valid=False),
Data("FILE-SK-ARES70"),
Data("FILE-SK-ARES90"),
Data("FILE-SK-POLICE"),
Data("FILE-SK-DOZER"),
Data("FILE-SK-EXCAVATOR"),
Data("FILE-R1306FC - Delta Bliss")
]