from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_PreciousList.html
# flake8: noqa
important_items_data: list[Data] = [
Data("Conners Comm Device"),
Data("Windshield Glass"),
Data("Bobbys Watch"),
Data("Gnarlbranch Sap"),
Data("Legen-dar"),
Data("Smelly Legen-dar"),
Data("Slice of Bread"),
Data("Deep Blue Gem"),
Data("Large Stuffed Lobster", valid=False),
Data("Stuffed Lobster", count=99),
Data("Meal Ticket", valid=False),
Data("Suid Bones", valid=False),
Data("Ma-non Hunting Kit", valid=False),
Data("Bronze Blatta Card", valid=False),
Data("Bronze Cinicula Card", valid=False),
Data("Bronze Petramand Card", valid=False),
Data("Silver Simius Card", valid=False),
Data("Silver Evello Card", valid=False),
Data("Silver Xiphias Card", valid=False),
Data("Silver Mortifole Card", valid=False),
Data("Gold Nopopotamus Card"),
Data("ITM_PRC022_Name", valid=False),
Data("Natural Pearl", count=10),
Data("ITM_PRC024_Name", valid=False),
Data("ITM_PRC025_Name", valid=False),
Data("ITM_PRC026_Name", valid=False),
Data("ITM_PRC027_Name", valid=False),
Data("ITM_PRC028_Name", valid=False),
Data("ITM_PRC029_Name", valid=False),
Data("ITM_PRC030_Name", valid=False),
Data("ITM_PRC031_Name", valid=False),
Data("White Gold Ore"),
Data("Briggss Key"),
Data("Fosdykes Key", count=0),
Data("Moorehouses Key", count=0),
Data("ITM_PRC036_Name", valid=False),
Data("ITM_PRC037_Name", valid=False),
Data("ITM_PRC038_Name", valid=False),
Data("Queggas Note"),
Data("ITM_PRC040_Name", valid=False),
Data("ITM_PRC041_Name", valid=False),
Data("Keycard - Lakeside Getaway"),
Data("ID Card_1", valid=False),
Data("ID Card_2", valid=False),
Data("ID Card_3", valid=False),
Data("ITM_PRC046_Name", valid=False),
Data("Ajoas ID Card"),
Data("ITM_PRC048_Name", valid=False),
Data("ITM_PRC049_Name", valid=False),
Data("ITM_PRC050_Name", valid=False),
Data("Ice Cream Cake"),
Data("Malyteths Bottle"),
Data("ITM_PRC053_Name", valid=False),
Data("ITM_PRC054_Name", valid=False),
Data("Nopon Contract", count=4),
Data("ITM_PRC056_Name", valid=False),
Data("Nopon Gemstone"),
Data("ITM_PRC058_Name", valid=False),
Data("ITM_PRC059_Name", valid=False),
Data("ITM_PRC060_Name", valid=False),
Data("Vi Sezhas Bracelet"),
Data("Ge Jewhes Dagger"),
Data("ITM_PRC063_Name", valid=False),
Data("ITM_PRC064_Name", valid=False),
Data("Ringstone"),
Data("ITM_PRC066_Name", valid=False),
Data("ITM_PRC067_Name", valid=False),
Data("Zazazans Package"),
Data("Hazardous Container"),
Data("Hazardous Fuel Cell"),
Data("Nios IOU"),
Data("Sapphire Ring"),
Data("ITM_PRC073_Name", valid=False),
Data("ITM_PRC074_Name", valid=False),
Data("ITM_PRC075_Name", valid=False),
Data("ITM_PRC076_Name", valid=False),
Data("ITM_PRC077_Name", valid=False),
Data("ITM_PRC078_Name", valid=False),
Data("ITM_PRC079_Name", valid=False),
Data("ITM_PRC080_Name", valid=False),
Data("ITM_PRC081_Name", valid=False),
Data("Lumenoa Leaf"),
Data("Gorkwa"),
Data("Runtonams Right Arm"),
Data("ITM_PRC085_Name", valid=False),
Data("ITM_PRC086_Name", valid=False),
Data("Troylans Gorkwa Fake"),
Data("ITM_PRC088_Name", valid=False),
Data("ITM_PRC089_Name", valid=False),
Data("White Whale Parts", count=3),
Data("ITM_PRC091_Name", valid=False),
Data("ITM_PRC092_Name", valid=False),
Data("ITM_PRC093_Name", valid=False),
Data("Ians ID Card"),
Data("Nalus Present"),
Data("Dadapons Sunglasses"),
Data("Dodonga Treaty"),
Data("Dorian Treaty"),
Data("Wrothian Part", count=4),
Data("Med Kit NLA", count=5),
Data("Internment Camp Key"),
Data("ITM_PRC102_Name", valid=False),
Data("Skell License", count=0),
Data("ITM_PRC104_Name", valid=False),
Data("ITM_PRC105_Name", valid=False),
Data("ITM_PRC106_Name", valid=False),
Data("White_Whale_Parts_2", valid=False),
Data("L-002 Power Cable", count=3),
Data("Skell License Certificate", count=8),
Data("ITM_PRC110_Name", valid=False),
Data("ITM_PRC111_Name", valid=False),
Data("ITM_PRC112_Name", valid=False),
Data("ITM_PRC113_Name", valid=False),
Data("Tissue Sample"),
Data("Mias Comm Device"),
Data("Phosphorus-Tree Seed", count=6),
Data("Container Key"),
Data("ITM_PRC118_Name", valid=False),
Data("ITM_PRC119_Name", valid=False),
Data("ITM_PRC120_Name", valid=False),
Data("Grenade Pizza"),
Data("Frozen Pizza"),
Data("Ajibas Key"),
Data("Mujibas Key"),
Data("Dancers Clothes"),
Data("Crimson Tear"),
Data("ITM_PRC127_Name", valid=False),
Data("ITM_PRC128_Name", valid=False),
Data("ITM_PRC129_Name", valid=False),
Data("ITM_PRC130_Name", valid=False),
Data("ITM_PRC131_Name", valid=False),
Data("ITM_PRC132_Name", valid=False),
Data("ITM_PRC133_Name", valid=False),
Data("ITM_PRC134_Name", valid=False),
Data("New Weapon Blueprint"),
Data("ITM_PRC136_Name", valid=False),
Data("Summoning Goggles"),
Data("Senirapa Water"),
Data("ITM_PRC139_Name", valid=False),
Data("Zirtodiamond"),
Data("Golboggas Disk"),
Data("ITM_PRC142_Name", valid=False),
Data("Tykki Sap"),
Data("ITM_PRC144_Name", valid=False),
Data("Gray Keycard"),
Data("Rectangular Chest"),
Data("ITM_PRC147_Name", valid=False),
Data("ITM_PRC148_Name", valid=False),
Data("ITM_PRC149_Name", valid=False),
Data("ITM_PRC150_Name", valid=False),
Data("ITM_PRC151_Name", valid=False),
Data("ITM_PRC152_Name", valid=False),
Data("Kutas Cargo"),
Data("ITM_PRC154_Name", valid=False),
Data("Aerozium"),
Data("Guardian Etherscale"),
Data("ITM_PRC157_Name", valid=False),
Data("ITM_PRC158_Name", valid=False),
Data("ITM_PRC159_Name", valid=False),
Data("ITM_PRC160_Name", valid=False),
Data("ITM_PRC161_Name", valid=False),
Data("ITM_PRC162_Name", valid=False),
Data("Hilal Stronghold Key", valid=False),
Data("Mimeosome Left Arm"),
Data("L-002 Experimental Plant"),
Data("Reverends Journal"),
Data("Flemtide", count=5),
Data("Floatstone Shard"),
Data("Blood-Soaked Beast Fur"),
Data("Laws Pendant"),
Data("Three Swords"),
Data("Pearl Necklace", valid=False),
Data("Data Unit FN093"),
Data("Repair Kit"),
Data("Aganeba Alloy"),
Data("Cockpit Wreckage"),
Data("Engine Wreckage"),
Data("Zu Pharg Wreckage", count=3),
Data("Junk", valid=False),
Data("Data Unit FN094"),
Data("Mimeosome Head", count=0),
Data("Mimeosome Torso", count=0),
Data("Mimeosome Left Leg"),
Data("Mimeosome Right Leg"),
Data("First Barrier Key"),
Data("ITM_PRC186_Name", valid=False),
Data("Cleansing Moss"),
Data("Locket"),
Data("Star Sand"),
Data("Violet Crystal"),
Data("Emerian Relic"),
Data("Missing Drive"),
Data("Broken Data Probe"),
Data("Heart Stone"),
Data("ITM_PRC195_Name", valid=False),
Data("ITM_PRC196_Name", valid=False),
Data("Mount Mgando Stone"),
Data("Jelly Weeds"),
Data("New-Weapon Remains"),
Data("ITM_PRC200_Name", valid=False),
Data("ITM_PRC201_Name", valid=False),
Data("ITM_PRC202_Name", valid=False),
Data("Sampling Bottle"),
Data("Solar Starship Map"),
Data("Hamburger"),
Data("Hot Dog"),
Data("Data Unit FN095"),
Data("Data Unit FN096"),
Data("Data Unit FN097"),
Data("Practice Data Probe"),
Data("Toxic Chemical Bomb"),
Data("Med Kit Ganglion", count=5),
Data("Noble Silk"),
Data("Data Unit FN098"),
Data("Sword of Legendaryness"),
Data("Unbreakable Sword"),
Data("Voltant"),
Data("Keycard - House of Cards"),
Data("Troylans Gorkwa"),
Data("Traditional Orphean Drug"),
Data("Weapon Test Data"),
Data("Second Barrier Key"),
Data("Third Barrier Key"),
Data("Phogrium"),
Data("Massive Ring Fragment"),
Data("Butte Ruin Fragments"),
Data("North Coast Riddle Rock"),
Data("Communication Data"),
Data("Medical Data"),
]