from ..Locations import Loc as Data

#https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_Location.html
# flake8: noqa
locations_data: list[Data] = [
Data("Barracks Interior"),
Data("Interior", regions=["Chapter 12"]),
Data("West Gate"),
Data("Central Industrial District"),
Data("Integrated Production Plant"),
Data("Outfitters Test Hangar"),
Data("Repenta Diner"),
Data("Professor Bs Lab", depends=["Mystery Man"]),
Data("West Melville Street"),
Data("Central Melville Street"),
Data("East Melville Street"),
Data("Barista Court"),
Data("North Founders Street"),
Data("Nopon Bazaar", depends=["BFFs"]),
Data("Deck", regions=["Chapter 5"]),
Data("Starboard", regions=["Chapter 5"]),
Data("Port Side", regions=["Chapter 5"], depends=["Prone Sweet Prone"]),
Data("Water Purification Plant"),
Data("Deliverance Park"),
Data("Cathedral"),
Data("Sports Complex"),
Data("Ishmael Hills"),
Data("Division Drive"),
Data("Armory Alley"),
Data("Yardleys Hideaway", depends=["House of Cards"]),
Data("East Gate"),
Data("BLADE Tower"),
Data("BLADE Concourse"),
Data("BLADE Barracks"),
Data("Mimeosome Maintenance Center"),
Data("Hangar"),
Data("Restricted Hangar Entrance"),
Data("Bedrock Hold"),
Data("Stonelattice Cavern", regions=["Skell License"]),  # maybe possible without if you MenuReset
Data("Greater Gemini Bridge"),
Data("Castaway Cavern"),
Data("Stickstone Rise"),
Data("Lesser Gemini Bridge"),
Data("Plundered Ruin"),
Data("Unicorn Rock"),
Data("Turtle Nest"),
Data("Molten Hollow"),
Data("Bedrock Hold Approach"),
Data("Biahno River"),
Data("Green Threshold"),
Data("Headwater Cavern"),
Data("Headwater Summit"),
Data("Headwater Cliff"),
Data("Biahno Water-Purification Plant", depends=["Water Woes"]),
Data("Biahno Lake"),
Data("Fallshorn Isle"),
Data("Grieving Plains"),
Data("Biahno Grassland"),
Data("Drop Shaft", depends=["Talon Rock Summit"]),
Data("Silent Mire"),
Data("Seaswept Base"),
Data("Wonderment Bluff"),
Data("Sickle Rock Rise"),
Data("Roof Rock"),
Data("Janpath Lake"),
Data("La Mancha"),
Data("North Janpath Plain"),
Data("Arendt Bridge"),
Data("Tallpach Peak"),
Data("Beasts Lair"),
Data("Northpointe Cove"),
Data("Northpointe Beach"),
Data("East Janpath Plain"),
Data("South Janpath Plain"),
Data("West Janpath Plain"),
Data("Cliffside Beach"),
Data("East Gate Plain"),
Data("West Gate Plain"),
Data("Talon Rock Prominence", depends=["Talon Rock Summit"]),
Data("Talon Rock Third Terrane"),
Data("Talon Rock Second Terrane"),
Data("Sayram Northeast Plain"),
Data("Shadow Rise"),
Data("Biahno Hills"),
Data("Starfall Basin"),
Data("Rock Cavern"),
Data("Seaswept Rise"),
Data("Sayram Lake"),
Data("Talon Rock Summit", regions=["Skell License"]),  # TAJ
Data("FN Site 101", regions=["FNet"]),
Data("FN Site 102", regions=["FNet"]),
Data("FN Site 103", regions=["FNet"]),
Data("FN Site 104", regions=["FNet"]),
Data("FN Site 106", regions=["FNet"]),
Data("Seaswept Ridge"),
Data("FN Site 108", regions=["FNet"]),
Data("FN Site 107", regions=["FNet"]),
Data("FN Site 109", regions=["FNet", "Skell License"]),
Data("FN Site 110", regions=["FNet"], depends=["Talon Rock Summit"]),
Data("FN Site 111", regions=["FNet"]),
Data("FN Site 112", regions=["FNet"]),
Data("FN Site 113", regions=["FNet"]),
Data("FN Site 114", regions=["FNet"]),
Data("FN Site 115", regions=["FNet"]),
Data("FN Site 116", regions=["FNet"]),
Data("FN Site 117", regions=["FNet"]),
Data("FN Site 118", regions=["FNet"]),
Data("FN Site 119", regions=["FNet"]),
Data("FN Site 120", regions=["FNet"]),
Data("FN Site 121", regions=["FNet"]),
Data("FN Site 105", regions=["FNet"]),
Data("Rustpool Banks"),
Data("Potters Rock"),
Data("Whales Gullet"),
Data("Rust Lake"),
Data("Waterway Tangle"),
Data("Ensanguined Font"),
Data("Lakeview Stronghold"),
Data("Jasper Incline"),
Data("Old Dragontail Tree"),
Data("Redsnake Pass"),
Data("Whales Nostril"),
Data("Yagamis Vista"),
Data("Sapphire Carpet"),
Data("Sapphire Table"),
Data("Garden Spring"),
Data("Tripod Rock"),
Data("Humdrum Peaks"),
Data("Goblins Narrow"),
Data("Sunlit Spring"),
Data("Orochis Belly"),
Data("Elephants Trunk"),
Data("Seabound Coil Tree"),
Data("Nopon Highroad"),
Data("Coil Tree Cape"),
Data("Decapotamon Vista"),
Data("Decapotamon"),
Data("Cascade Isle"),
Data("Serpentine Pass"),
Data("Vitriol Cesspool"),
Data("Qing Long Glade"),
Data("Rockmoles Burrow"),
Data("Fukai Pass"),
Data("Everwhelm Falls"),
Data("Sato Headwater"),
Data("Weeping Whitewood"),
Data("Ensconced Citadel"),
Data("Suncatch Ravine"),
Data("Middle Hushflood"),
Data("Great Trident Crossing"),
Data("Bloodpond Basin"),
Data("Millstone Ridge"),
Data("Dead Mans Gulch"),
Data("Sharks Jaws"),
Data("Dead Mans Ingress"),
Data("Upper Hushflood"),
Data("Divine Roost", regions=["Skell License"]),  # TAJ
Data("Whales Weeper"),
Data("Nopon Braidbridge"),
Data("Skybound Coil Tree"),
Data("Great Nail"),
Data("Bident Crossing"),
Data("Blackback Bridge"),
Data("Narcissus Tree"),
Data("Celestial Ascent"),
Data("Celestial Cleave", depends=["Divine Roost"]),
Data("Sentinels Nest", depends=["Divine Roost"]),
Data("Canopied Nightwood"),
Data("Lotus Keep Building Site"),
Data("Twin Hammers"),
Data("Breakwater Narrow"),
Data("Skygazers Atrium"),
Data("Idyll Beach"),
Data("FN Site 201", regions=["FNet"], depends=["Divine Roost"]),
Data("FN Site 202", regions=["FNet"]),
Data("FN Site 203", regions=["FNet"]),
Data("FN Site 204", regions=["FNet"]),
Data("FN Site 205", regions=["FNet"]),
Data("FN Site 206", regions=["FNet"], depends=["Divine Roost"]),
Data("FN Site 207", regions=["FNet"], depends=["Divine Roost"]),
Data("FN Site 208", regions=["FNet"]),
Data("FN Site 209", regions=["FNet"]),
Data("FN Site 210", regions=["FNet"]),
Data("FN Site 211", regions=["FNet"]),
Data("FN Site 212", regions=["FNet"]),
Data("FN Site 213", regions=["FNet"], depends=["Divine Roost"]),
Data("FN Site 214", regions=["FNet"]),
Data("FN Site 215", regions=["FNet"]),
Data("FN Site 216", regions=["FNet"]),
Data("FN Site 217", regions=["FNet"]),
Data("FN Site 218", regions=["FNet"]),
Data("FN Site 219", regions=["FNet"]),
Data("FN Site 220", regions=["FNet"]),
Data("FN Site 221", regions=["FNet"]),
Data("FN Site 222", regions=["FNet"]),
Data("FN Site 223", regions=["FNet"]),
Data("FN Site 224", regions=["FNet"]),
Data("FN Site 225", regions=["FNet"]),
Data("Oblivia Ingress"),
Data("Yawning Giant"),
Data("Mesa Fortress"),
Data("Demons Pocket", regions=["Skell License"]),  # TAJ helpful but i guess not required
Data("Scabland Fortress"),
Data("River Isle"),
Data("Rooney Cavern"),
Data("Atop the Giant Ring"),  # advanced jump but long detour via Primeval Meadow
Data("Ejiri Promontory"),
Data("Leaning Ring"),
Data("Drowning Ring"),
Data("Beachside Trove"),
Data("Azure Lagoon"),
Data("Balance Rock"),
Data("South Coast"),
Data("Barbarich Desert"),
Data("Primeval Meadow"),  # advanced jump but long debtour
Data("Cryptic Sign", regions=["Skell License"]),  # maybe TAJ
Data("Jair Fortress"),
Data("Sea Whisper Valley"),
Data("West Ibra Ravine"),
Data("Central Ibra Ravine"),
Data("East Ibra Ravine"),
Data("Victory Rock"),
Data("Alexander Ridge"),
Data("Wrothian Stronghold", depends=["A Challenger Approaches"]),
Data("Dorian Caravan"),
Data("Lake Basel"),
Data("Floating Reef", regions=["Flight Module"]),  # technically accessable with only a skell but really really hard
Data("Ruins on the Sandbank"),
Data("Kings Falls"),
Data("Milligan Supply Base"),
Data("North Coast"),
Data("Big Arch"),
Data("Ruins on the Butte"),
Data("Kintrees"),  # advanced jump via Beehive Rock
Data("Aaroy Plain"),
Data("Twin Arches"),
Data("Devils Colony"),
Data("Great Washington Isle", regions=["Skell License"]),
Data("Cliffside Camp"),
Data("Crater Oasis"),
Data("North Ants Nest"),
Data("Ants Nest"),  # not sure what this even is
Data("South Ants Nest"),
Data("Keegan Ridge"),
Data("Stoyanov Trail"),
Data("Mount Edge Peak", regions=["Skell License"]),  # needs a few ramps
Data("Beehive Rock"),  # advanced jump from above
Data("Eddies Conquest"), # advanced jump
Data("FN Site 301", regions=["FNet"]),
Data("FN Site 302", regions=["FNet"]),
Data("FN Site 303", regions=["FNet"]),
Data("FN Site 304", regions=["FNet"]),
Data("FN Site 305", regions=["FNet"]),
Data("FN Site 306", regions=["FNet"]),
Data("FN Site 307", regions=["FNet"]),
Data("FN Site 308", regions=["FNet"]),
Data("FN Site 309", regions=["FNet"]),
Data("FN Site 310", regions=["FNet"]), # advanced jump
Data("FN Site 311", regions=["FNet"]),
Data("FN Site 312", regions=["FNet"]),
Data("FN Site 313", regions=["FNet"]),
Data("FN Site 314", regions=["FNet"]),
Data("FN Site 315", regions=["FNet"]),
Data("FN Site 316", regions=["FNet"]),
Data("FN Site 317", regions=["FNet"]),
Data("FN Site 318", regions=["FNet"]),
Data("FN Site 320", regions=["FNet"], depends=["Floating Reef"]),
Data("FN Site 321", regions=["FNet"]),
Data("FN Site 319", regions=["FNet"]),
Data("FN Site 322", regions=["FNet"]),
Data("Seabirds Beak"),
Data("Needle Rock Sandsea"),
Data("South Silent Sandsea"),
Data("North Silent Sandsea"),
Data("Lake Ciel"),
Data("South Ciel Sandsea"),
Data("West Ciel Sandsea"),
Data("East Ciel Sandsea"),
Data("North Ciel Sandsea"),
Data("Shivering Sands"),
Data("Xanadu Overlook"),
Data("Cleansing Spring"),
Data("Badr Stonebridge"),
Data("Anvil Rock Two"),
Data("Anvil Rock One"),
Data("Anvil Sandplain"),
Data("South Hardheart Canyon"),
Data("Hardheart Canyon"),
Data("North Hardheart Canyon"),
Data("Southern Searoad"),
Data("Sylvalum Searoad"),
Data("Northern Searoad"),
Data("Delusians North Summit"),
Data("Gehenna Span"),
Data("Delusians South Summit"),
Data("South Cinderdunes"),
Data("West Cinderdunes"),
Data("North Cinderdunes"),
Data("Samuel Incline"),
Data("Cauldros Threshold"),
Data("Hilal Meadow"),
Data("Hilal Stronghold"),
Data("Badr Basin"),
Data("Badr Stronghold"),
Data("Secluded Lava Lake"),
Data("Cavernous Abyss", regions=["Skell License"]),  # TAJ
Data("Banshee Cave"),
Data("Quay Hollows", regions=["Skell License"]),  # TAJ
Data("Den of the Dead"),  # from above with jump
Data("Behemoths Shadows"),
Data("Sandsprint Slope"),
Data("Lesser Anvil"),  # available from below but needs skell to get on top
Data("Arc Rock", regions=["Skell License"]),  # TAJ
Data("Abyss Reservoir", depends=["Cavernous Abyss"]),
Data("Noctilucent Sphere", regions=["Skell License"]),  # TAJ
Data("Lower Delusian Mountains"),
Data("Sandsprint Cavity"),  # advanced jump, MenuReset from south side top because north has invisible wall
Data("Noctilucent Sphere Interior", depends=["Noctilucent Sphere"]),
Data("FN Site 401", regions=["FNet"]),
Data("FN Site 402", regions=["FNet"]),
Data("FN Site 403", regions=["FNet"]),
Data("FN Site 404", regions=["FNet"]),
Data("FN Site 405", regions=["FNet"]),
Data("FN Site 406", regions=["FNet"]),
Data("FN Site 407", regions=["FNet"]),
Data("FN Site 408", regions=["FNet"]),
Data("FN Site 409", regions=["FNet"]),
Data("FN Site 410", regions=["FNet"]),
Data("FN Site 411", regions=["FNet"]),
Data("FN Site 412", regions=["FNet"]),
Data("FN Site 413", regions=["FNet"]),
Data("FN Site 414", regions=["FNet"]),
Data("FN Site 415", regions=["FNet"]),
Data("FN Site 416", regions=["FNet"]),
Data("FN Site 417", regions=["FNet"]),
Data("FN Site 418", regions=["FNet"]),
Data("FN Site 419", regions=["FNet"]),
Data("FN Site 420", regions=["FNet"]),
Data("Drongo Caravan"),
Data("Scholes Battlegrounds"),
Data("Infernal Ledges"),
Data("Ancient Warscape"),
Data("Wildcat Fortress"),
Data("White Phosphor Lake"),
Data("Orrh Sim Gate"),
Data("Ganglion Antropolis"),  # accessable but not inside without mission
Data("Ruined City of Orrh Sim"),
Data("Gnahan Villa"),
Data("Emerian Battlegrounds"),
Data("Forgotten Mining Frigates"),
Data("Adder Byroad"),
Data("Bandits Refuge"),
Data("Slavebird Isle"),  # advanced jump
Data("Ganglion Weapons Hangar"),
Data("Orrh Sim Castle Ruins"),
Data("Tengus Playground"),
Data("Tphnom Shelf"),
Data("Kitsune Stronghold"),
Data("Sunset Falls"),
Data("Kwarah Villa"),
Data("Kwarah Cloister"),
Data("Boxtrap Checkpoint"),
Data("Mgando Mineral Spring"),
Data("Bestial Utopia"),
Data("Mgando Volcanic Crater"),
Data("Mount Mgando"),
Data("Old Ceremonial Hollow"),  # might be the other one
Data("Old Ceremonial Hollow_1", valid=False),
Data("Beneath Orrh Sim Keep"),
Data("Dragonbone Promontory"),
Data("Ternion Fork"),
Data("Abandoned Bivouac"),
Data("Mgando Gorge"),
Data("Titans Table"),
Data("Cauldros Gate"),
Data("Capital Wreckage"),
Data("Orrh Sim Capital Remains"),
Data("Orrh Sim Watchtowers"),
Data("Far Isle of Tzuo"),
Data("FN Site 501", regions=["FNet"]),
Data("FN Site 502", regions=["FNet"]),
Data("FN Site 503", regions=["FNet"]),
Data("FN Site 504", regions=["FNet"]),
Data("FN Site 505", regions=["FNet"]),
Data("FN Site 506", regions=["FNet"]),
Data("FN Site 507", regions=["FNet"]),
Data("FN Site 508", regions=["FNet"]),
Data("FN Site 509", regions=["FNet"]),
Data("FN Site 510", regions=["FNet"]),
Data("FN Site 511", regions=["FNet"]),
Data("FN Site 512", regions=["FNet"]),
Data("FN Site 513", regions=["FNet"]),
Data("FN Site 514", regions=["FNet"]),
Data("FN Site 515", regions=["FNet"]),
Data("FN Site 516", regions=["FNet"]),
Data("Shadow Rise BC"),
Data("Shadow Beach BC"),
Data("East Gate BC"),
Data("South Janpath BC"),
Data("Biahno Grassland BC"),
Data("North Janpath BC"),
Data("Sayram Lake BC"),
Data("Roof Rock BC"),
Data("camp1501_09", valid=False),
Data("camp1501_10", valid=False),
Data("Rustpool Banks BC"),
Data("Whales Nostril BC"),
Data("Tripod Rock BC"),
Data("Canopied Nightwood BC"),
Data("Decapotamon BC"),
Data("Qing Long Glade BC"),
Data("Bloodpond Basin BC"),
Data("Dead Mans Ingress BC"),
Data("camp1601_09", valid=False),
Data("camp1601_10", valid=False),
Data("Oblivia Ingress BC"),
Data("Aaroy Plain BC"),
Data("Needle Bridge BC"),
Data("Broken Hill BC"),
Data("River Isle BC"),
Data("Balance Rock BC"),
Data("North Coast BC"),
Data("Cliffs Edge BC"),
Data("camp1701_09", valid=False),
Data("camp1701_10", valid=False),
Data("Ancient Warscape BC"),
Data("Titans Table BC"),
Data("Emerian Battlegrounds BC"),
Data("Rocky Lagoon BC"),
Data("Adder Byroad BC"),
Data("Ternion Fork BC"),
Data("Tphnom Shelf BC"),
Data("Mgando Gorge BC"),
Data("camp2001_09", valid=False),
Data("camp2001_10", valid=False),
Data("Seabirds Beak BC"),
Data("Needle Rock BC"),
Data("NW Ciel Sandsea BC"),
Data("Hardheart Ravine BC"),
Data("Delusians North Summit BC"),
Data("Samuel Incline BC"),
Data("North Silent Sandsea BC"),
Data("Cauldros Threshold BC"),
Data("camp2201_09", valid=False),
Data("camp2201_10", valid=False),
Data("NLA Last Defense Line", regions=["Chapter 8"]),
Data("NLA Primary Defense Line", regions=["Chapter 8"]),
Data("Zu Pharg Interception Line", regions=["Chapter 10"]),
Data("Lifehold Core", regions=["Chapter 12"]),
Data("Orrh Sim Keep"),
]