from rule_builder.options import OptionFilter
from rule_builder.rules import Has, Rule
from worlds.xenobladex.Options import IncludeImportantItems

opt_imp_itms = [OptionFilter(IncludeImportantItems, IncludeImportantItems.option_on)]

important_item_rules: dict[str, Rule] = {
    "Conners Comm Device": Has("IMPIT: Conners Comm Device", options=opt_imp_itms, filtered_resolution=True),
    "Windshield Glass": Has("IMPIT: Windshield Glass", options=opt_imp_itms, filtered_resolution=True),
    "Bobbys Watch": Has("IMPIT: Bobbys Watch", options=opt_imp_itms, filtered_resolution=True),
    "Gnarlbranch Sap": Has("IMPIT: Gnarlbranch Sap", options=opt_imp_itms, filtered_resolution=True),
    "Legen-dar": Has("IMPIT: Legen-dar", options=opt_imp_itms, filtered_resolution=True),
    "Smelly Legen-dar": Has("IMPIT: Smelly Legen-dar", options=opt_imp_itms, filtered_resolution=True),
    "Slice of Bread": Has("IMPIT: Slice of Bread", options=opt_imp_itms, filtered_resolution=True),
    "Deep Blue Gem": Has("IMPIT: Deep Blue Gem", options=opt_imp_itms, filtered_resolution=True),
    "Stuffed Lobster": Has("IMPIT: Stuffed Lobster", 99, options=opt_imp_itms, filtered_resolution=True),
    "Gold Nopopotamus Card": Has("IMPIT: Gold Nopopotamus Card", options=opt_imp_itms, filtered_resolution=True),
    "Natural Pearl": Has("IMPIT: Natural Pearl", 10, options=opt_imp_itms, filtered_resolution=True),
    "White Gold Ore": Has("IMPIT: White Gold Ore", options=opt_imp_itms, filtered_resolution=True),
    "Briggss Key": Has("IMPIT: Briggss Key", options=opt_imp_itms, filtered_resolution=True),
    # after the celeste three
    # "Fosdykes Key": Has("IMPIT: Fosdykes Key", options=opt_imp_itms, filtered_resolution=True),
    # "Moorehouses Key": Has("IMPIT: Moorehouses Key", options=opt_imp_itms, filtered_resolution=True),
    "Queggas Note": Has("IMPIT: Queggas Note", options=opt_imp_itms, filtered_resolution=True),
    "Keycard Lakeside Getaway": Has("IMPIT: Keycard - Lakeside Getaway",
                                    options=opt_imp_itms, filtered_resolution=True),
    "Ajoas ID Card": Has("IMPIT: Ajoas ID Card", options=opt_imp_itms, filtered_resolution=True),
    "Ice Cream Cake": Has("IMPIT: Ice Cream Cake", options=opt_imp_itms, filtered_resolution=True),
    "Malyteths Bottle": Has("IMPIT: Malyteths Bottle", options=opt_imp_itms, filtered_resolution=True),
    "Nopon Contract": Has("IMPIT: Nopon Contract", 4, options=opt_imp_itms, filtered_resolution=True),
    "Nopon Gemstone": Has("IMPIT: Nopon Gemstone", options=opt_imp_itms, filtered_resolution=True),
    "Vi Sezhas Bracelet": Has("IMPIT: Vi Sezhas Bracelet", options=opt_imp_itms, filtered_resolution=True),
    "Ge Jewhes Dagger": Has("IMPIT: Ge Jewhes Dagger", options=opt_imp_itms, filtered_resolution=True),
    "Ringstone": Has("IMPIT: Ringstone", options=opt_imp_itms, filtered_resolution=True),
    "Zazazans Package": Has("IMPIT: Zazazans Package", options=opt_imp_itms, filtered_resolution=True),
    "Hazardous Container": Has("IMPIT: Hazardous Container", options=opt_imp_itms, filtered_resolution=True),
    "Hazardous Fuel Cell": Has("IMPIT: Hazardous Fuel Cell", options=opt_imp_itms, filtered_resolution=True),
    "Nios IOU": Has("IMPIT: Nios IOU", options=opt_imp_itms, filtered_resolution=True),
    "Sapphire Ring": Has("IMPIT: Sapphire Ring", options=opt_imp_itms, filtered_resolution=True),
    "Lumenoa Leaf": Has("IMPIT: Lumenoa Leaf", options=opt_imp_itms, filtered_resolution=True),
    "Gorkwa": Has("IMPIT: Gorkwa", options=opt_imp_itms, filtered_resolution=True),
    "Runtonams Right Arm": Has("IMPIT: Runtonams Right Arm", options=opt_imp_itms, filtered_resolution=True),
    "Troylans Gorkwa Fake": Has("IMPIT: Troylans Gorkwa Fake", options=opt_imp_itms, filtered_resolution=True),
    "White Whale Parts": Has("IMPIT: White Whale Parts", 3, options=opt_imp_itms, filtered_resolution=True),
    "Ians ID Card": Has("IMPIT: Ians ID Card", options=opt_imp_itms, filtered_resolution=True),
    "Nalus Present": Has("IMPIT: Nalus Present", options=opt_imp_itms, filtered_resolution=True),
    "Dadapons Sunglasses": Has("IMPIT: Dadapons Sunglasses", options=opt_imp_itms, filtered_resolution=True),
    "Dodonga Treaty": Has("IMPIT: Dodonga Treaty", options=opt_imp_itms, filtered_resolution=True),
    "Dorian Treaty": Has("IMPIT: Dorian Treaty", options=opt_imp_itms, filtered_resolution=True),
    "Wrothian Part": Has("IMPIT: Wrothian Part", 3, options=opt_imp_itms, filtered_resolution=True),
    "Med Kit NLA": Has("IMPIT: Med Kit NLA", 5, options=opt_imp_itms, filtered_resolution=True),
    "Internment Camp Key": Has("IMPIT: Internment Camp Key", options=opt_imp_itms, filtered_resolution=True),
    # after the skell license
    # "Skell License": Has("IMPIT: Skell License", options=opt_imp_itms, filtered_resolution=True),
    # probably unused
    # "White Whale Parts_2": Has("IMPIT: White Whale Parts_2", options=opt_imp_itms, filtered_resolution=True),
    "L-002 Power Cable": Has("IMPIT: L-002 Power Cable", 3, options=opt_imp_itms, filtered_resolution=True),
    "Skell License Certificate": Has("IMPIT: Skell License Certificate", 8,
                                     options=opt_imp_itms, filtered_resolution=True),
    "Tissue Sample": Has("IMPIT: Tissue Sample", options=opt_imp_itms, filtered_resolution=True),
    "Mias Comm Device": Has("IMPIT: Mias Comm Device", options=opt_imp_itms, filtered_resolution=True),
    "Phosphorus-Tree Seed": Has("IMPIT: Phosphorus-Tree Seed", 6, options=opt_imp_itms, filtered_resolution=True),
    "Container Key": Has("IMPIT: Container Key", options=opt_imp_itms, filtered_resolution=True),
    "Grenade Pizza": Has("IMPIT: Grenade Pizza", options=opt_imp_itms, filtered_resolution=True),
    "Frozen Pizza": Has("IMPIT: Frozen Pizza", options=opt_imp_itms, filtered_resolution=True),
    "Ajibas Key": Has("IMPIT: Ajibas Key", options=opt_imp_itms, filtered_resolution=True),
    "Mujibas Key": Has("IMPIT: Mujibas Key", options=opt_imp_itms, filtered_resolution=True),
    "Dancers Clothes": Has("IMPIT: Dancers Clothes", options=opt_imp_itms, filtered_resolution=True),
    "Crimson Tear": Has("IMPIT: Crimson Tear", options=opt_imp_itms, filtered_resolution=True),
    "New Weapon Blueprint": Has("IMPIT: New Weapon Blueprint", options=opt_imp_itms, filtered_resolution=True),
    "Summoning Goggles": Has("IMPIT: Summoning Goggles", options=opt_imp_itms, filtered_resolution=True),
    "Senirapa Water": Has("IMPIT: Senirapa Water", options=opt_imp_itms, filtered_resolution=True),
    "Zirtodiamond": Has("IMPIT: Zirtodiamond", options=opt_imp_itms, filtered_resolution=True),
    "Golboggas Disk": Has("IMPIT: Golboggas Disk", options=opt_imp_itms, filtered_resolution=True),
    "Tykki Sap": Has("IMPIT: Tykki Sap", options=opt_imp_itms, filtered_resolution=True),
    "Gray Keycard": Has("IMPIT: Gray Keycard", options=opt_imp_itms, filtered_resolution=True),
    "Rectangular Chest": Has("IMPIT: Rectangular Chest", options=opt_imp_itms, filtered_resolution=True),
    "Kutas Cargo": Has("IMPIT: Kutas Cargo", options=opt_imp_itms, filtered_resolution=True),
    "Aerozium": Has("IMPIT: Aerozium", options=opt_imp_itms, filtered_resolution=True),
    "Guardian Etherscale": Has("IMPIT: Guardian Etherscale", options=opt_imp_itms, filtered_resolution=True),
    # affinity mission arms and the men
    "Mimeosome Left Arm": Has("IMPIT: Mimeosome Left Arm", options=opt_imp_itms, filtered_resolution=True),
    "L-002 Experimental Plant": Has("IMPIT: L-002 Experimental Plant", options=opt_imp_itms, filtered_resolution=True),
    "Reverends Journal": Has("IMPIT: Reverends Journal", options=opt_imp_itms, filtered_resolution=True),
    "Flemtide": Has("IMPIT: Flemtide", 5, options=opt_imp_itms, filtered_resolution=True),
    "Floatstone Shard": Has("IMPIT: Floatstone Shard", options=opt_imp_itms, filtered_resolution=True),
    "Blood-Soaked Beast Fur": Has("IMPIT: Blood-Soaked Beast Fur", options=opt_imp_itms, filtered_resolution=True),
    "Laws Pendant": Has("IMPIT: Laws Pendant", options=opt_imp_itms, filtered_resolution=True),
    "Three Swords": Has("IMPIT: Three Swords", options=opt_imp_itms, filtered_resolution=True),
    "Data Unit FN093": Has("IMPIT: Data Unit FN093", options=opt_imp_itms, filtered_resolution=True),
    "Repair Kit": Has("IMPIT: Repair Kit", options=opt_imp_itms, filtered_resolution=True),
    "Aganeba Alloy": Has("IMPIT: Aganeba Alloy", options=opt_imp_itms, filtered_resolution=True),
    "Cockpit Wreckage": Has("IMPIT: Cockpit Wreckage", options=opt_imp_itms, filtered_resolution=True),
    "Engine Wreckage": Has("IMPIT: Engine Wreckage", options=opt_imp_itms, filtered_resolution=True),
    "Zu Pharg Wreckage": Has("IMPIT: Zu Pharg Wreckage", 3, options=opt_imp_itms, filtered_resolution=True),
    "Data Unit FN094": Has("IMPIT: Data Unit FN094", options=opt_imp_itms, filtered_resolution=True),
    # obtainable after yelvs partner
    # "Mimeosome Head": Has("IMPIT: Mimeosome Head", options=opt_imp_itms, filtered_resolution=True),
    # "Mimeosome Torso": Has("IMPIT: Mimeosome Torso", options=opt_imp_itms, filtered_resolution=True),
    # required for yelvs partner. obtainable after arms and the man
    "Mimeosome Left Leg": Has("IMPIT: Mimeosome Left Leg", options=opt_imp_itms, filtered_resolution=True),
    # required for yelvs partner. obtainable after arms and the man
    "Mimeosome Right Leg": Has("IMPIT: Mimeosome Right Leg", options=opt_imp_itms, filtered_resolution=True),
    "First Barrier Key": Has("IMPIT: First Barrier Key", options=opt_imp_itms, filtered_resolution=True),
    # basic mission clean and green
    "Cleansing Moss": Has("IMPIT: Cleansing Moss", options=opt_imp_itms, filtered_resolution=True),
    "Locket": Has("IMPIT: Locket", options=opt_imp_itms, filtered_resolution=True),  # basic mission lost memento
    # basic mission star sand seeker
    "Star Sand": Has("IMPIT: Star Sand", options=opt_imp_itms, filtered_resolution=True),
    # basic mission a hard pill to swallow
    "Violet Crystal": Has("IMPIT: Violet Crystal", options=opt_imp_itms, filtered_resolution=True),
    # basic mission the emerian battlegrounds
    "Emerian Relic": Has("IMPIT: Emerian Relic", options=opt_imp_itms, filtered_resolution=True),
    # basic mission data recovery
    "Missing Drive": Has("IMPIT: Missing Drive", options=opt_imp_itms, filtered_resolution=True),
    # basic mission a probing issue
    "Broken Data Probe": Has("IMPIT: Broken Data Probe", options=opt_imp_itms, filtered_resolution=True),
    # basic mission straight from the heart
    "Heart Stone": Has("IMPIT: Heart Stone", options=opt_imp_itms, filtered_resolution=True),
    # basic mission mount mgando mineralogy
    "Mount Mgando Stone": Has("IMPIT: Mount Mgando Stone", options=opt_imp_itms, filtered_resolution=True),
    # basic mission in a jam
    "Jelly Weeds": Has("IMPIT: Jelly Weeds", options=opt_imp_itms, filtered_resolution=True),
    # basic mission test data retrieval
    "New-Weapon Remains": Has("IMPIT: New-Weapon Remains", options=opt_imp_itms, filtered_resolution=True),
    "Sampling Bottle": Has("IMPIT: Sampling Bottle", options=opt_imp_itms, filtered_resolution=True),
    # required for proficiency exam 4, which itself is just a skell license certificate
    "Solar Starship Map": Has("IMPIT: Solar Starship Map", options=opt_imp_itms, filtered_resolution=True),
    "Hamburger": Has("IMPIT: Hamburger", options=opt_imp_itms, filtered_resolution=True),
    "Hot Dog": Has("IMPIT: Hot Dog", options=opt_imp_itms, filtered_resolution=True),
    "Data Unit FN095": Has("IMPIT: Data Unit FN095", options=opt_imp_itms, filtered_resolution=True),
    "Data Unit FN096": Has("IMPIT: Data Unit FN096", options=opt_imp_itms, filtered_resolution=True),
    "Data Unit FN097": Has("IMPIT: Data Unit FN097", options=opt_imp_itms, filtered_resolution=True),
    "Practice Data Probe": Has("IMPIT: Practice Data Probe", options=opt_imp_itms, filtered_resolution=True),
    "Toxic Chemical Bomb": Has("IMPIT: Toxic Chemical Bomb", options=opt_imp_itms, filtered_resolution=True),
    "Med Kit Ganglion": Has("IMPIT: Med Kit Ganglion", 5, options=opt_imp_itms, filtered_resolution=True),
    "Noble Silk": Has("IMPIT: Noble Silk", options=opt_imp_itms, filtered_resolution=True),
    "Data Unit FN098": Has("IMPIT: Data Unit FN098", options=opt_imp_itms, filtered_resolution=True),
    "Sword of Legendaryness": Has("IMPIT: Sword of Legendaryness", options=opt_imp_itms, filtered_resolution=True),
    "Unbreakable Sword": Has("IMPIT: Unbreakable Sword", options=opt_imp_itms, filtered_resolution=True),
    # # probably not required for the good thief
    # "Voltant": Has("IMPIT: Voltant", options=opt_imp_itms, filtered_resolution=True),
    "Keycard House of Cards": Has("IMPIT: Keycard - House of Cards", options=opt_imp_itms, filtered_resolution=True),
    "Troylans Gorkwa": Has("IMPIT: Troylans Gorkwa", options=opt_imp_itms, filtered_resolution=True),
    "Traditional Orphean Drug": Has("IMPIT: Traditional Orphean Drug", options=opt_imp_itms, filtered_resolution=True),
    "Weapon Test Data": Has("IMPIT: Weapon Test Data", options=opt_imp_itms, filtered_resolution=True),
    "Second Barrier Key": Has("IMPIT: Second Barrier Key", options=opt_imp_itms, filtered_resolution=True),
    "Third Barrier Key": Has("IMPIT: Third Barrier Key", options=opt_imp_itms, filtered_resolution=True),
    "Phogrium": Has("IMPIT: Phogrium", options=opt_imp_itms, filtered_resolution=True),
    "Massive Ring Fragment": Has("IMPIT: Massive Ring Fragment", options=opt_imp_itms, filtered_resolution=True),
    "Butte Ruin Fragments": Has("IMPIT: Butte Ruin Fragments", options=opt_imp_itms, filtered_resolution=True),
    "North Coast Riddle Rock": Has("IMPIT: North Coast Riddle Rock", options=opt_imp_itms, filtered_resolution=True),
    "Communication Data": Has("IMPIT: Communication Data", options=opt_imp_itms, filtered_resolution=True),
    "Medical Data": Has("IMPIT: Medical Data", options=opt_imp_itms, filtered_resolution=True),
}
