# map completion checks
container_ride_completion = "Container Ride Completion"
portal_carousel_completion = "Portal Carousel Completion"
portal_gun_completion = "Portal Gun Completion"
smooth_jazz_completion = "Smooth Jazz Completion"
cube_momentum_completion = "Cube Momentum Completion"
future_starter_completion = "Future Starter Completion"
secret_panel_completion = "Secret Panel Completion"
wake_up_completion = "Wake Up Completion"
incinerator_completion = "Incinerator Completion"
laser_intro_completion = "Laser Intro Completion"
laser_stairs_completion = "Laser Stairs Completion"
dual_lasers_completion = "Dual Lasers Completion"
laser_over_goo_completion = "Laser Over Goo Completion"
catapult_intro_completion = "Catapult Intro Completion"
trust_fling_completion = "Trust Fling Completion"
pit_flings_completion = "Pit Flings Completion"
fizzler_intro_completion = "Fizzler Intro Completion"
ceiling_catapult_completion = "Ceiling Catapult Completion"
ricochet_completion = "Ricochet Completion"
bridge_intro_completion = "Bridge Intro Completion"
bridge_the_gap_completion = "Bridge the Gap Completion"
turret_intro_completion = "Turret Intro Completion"
laser_relays_completion = "Laser Relays Completion"
turret_blocker_completion = "Turret Blocker Completion"
laser_vs_turret_completion = "Laser Vs. Turret Completion"
pull_the_rug_completion = "Pull The Rug Completion"
column_blocker_completion = "Column Blocker Completion"
laser_chaining_completion = "Laser Chaining Completion"
triple_laser_completion = "Triple Laser Completion"
jailbreak_completion = "Jailbreak Completion"
escape_completion = "Escape Completion"
turret_factory_completion = "Turret Factory Completion"
turret_sabotage_completion = "Turret Sabotage Completion"
neurotoxin_sabotage_completion = "Neurotoxin Sabotage Completion"
core_completion = "Core Completion"
underground_completion = "Underground Completion"
cave_johnson_completion = "Cave Johnson Completion"
repulsion_intro_completion = "Repulsion Intro Completion"
bomb_flings_completion = "Bomb Flings Completion"
crazy_box_completion = "Crazy Box Completion"
potatos_completion = "PotatOS Completion"
propulsion_intro_completion = "Propulsion Intro Completion"
propulsion_flings_completion = "Propulsion Flings Completion"
conversion_intro_completion = "Conversion Intro Completion"
three_gels_completion = "Three Gels Completion"
test_completion = "Test Completion"
funnel_intro_completion = "Funnel Intro Completion"
ceiling_button_completion = "Ceiling Button Completion"
wall_button_completion = "Wall Button Completion"
polarity_completion = "Polarity Completion"
funnel_catch_completion = "Funnel Catch Completion"
stop_the_box_completion = "Stop The Box Completion"
laser_catapult_completion = "Laser Catapult Completion"
laser_platform_completion = "Laser Platform Completion"
propulsion_catch_completion = "Propulsion Catch Completion"
repulsion_polarity_completion = "Repulsion Polarity Completion"
finale_1_completion = "Finale 1 Completion"
finale_2_completion = "Finale 2 Completion"
finale_3_completion = "Finale 3 Completion"
finale_4_completion = "Finale 4 Completion"

# optional checks
tube_ride_completion = "Tube Ride Completion"
long_fall_completion = "Long Fall Completion"

# wheatley monitors
wheatley_monitor_1_funnel_intro = "Wheatley Monitor 1 (Funnel Intro)"
wheatley_monitor_2_ceiling_button = "Wheatley Monitor 2 (Ceiling Button)"
wheatley_monitor_3_wall_button = "Wheatley Monitor 3 (Wall Button)"
wheatley_monitor_4_polarity = "Wheatley Monitor 4 (Polarity)"
wheatley_monitor_5_funnel_catch = "Wheatley Monitor 5 (Funnel Catch)"
wheatley_monitor_6_funnel_catch = "Wheatley Monitor 6 (Funnel Catch)"
wheatley_monitor_7_stop_the_box = "Wheatley Monitor 7 (Stop The Box)"
wheatley_monitor_8_laser_catapult = "Wheatley Monitor 8 (Laser Catapult)"
wheatley_monitor_9_laser_platform = "Wheatley Monitor 9 (Laser Platform)"
wheatley_monitor_10_propulsion_catch = "Wheatley Monitor 10 (Propulsion Catch)"
wheatley_monitor_11_repulsion_polarity = "Wheatley Monitor 11 (Repulsion Polarity)"
wheatley_monitor_12_finale_3 = "Wheatley Monitor 12 (Finale 3)"

# ratman dens
ratman_den_1_smooth_jazz = "Ratman Den 1 (Smooth Jazz)"
ratman_den_2_dual_lasers = "Ratman Den 2 (Dual Lasers)"
ratman_den_3_trust_fling = "Ratman Den 3 (Trust Fling)"
ratman_den_4_bridge_intro = "Ratman Den 4 (Bridge Intro)"
ratman_den_5_bridge_the_gap = "Ratman Den 5 (Bridge the Gap)"
ratman_den_6_laser_vs_turret = "Ratman Den 6 (Laser Vs. Turret)"
ratman_den_7_pull_the_rug = "Ratman Den 7 (Pull The Rug)"

# vitrified doors
vitrified_door_1_cave_johnson = "Vitrified Door 1 (Cave Johnson)"
vitrified_door_2_cave_johnson = "Vitrified Door 2 (Cave Johnson)"
vitrified_door_3_cave_johnson = "Vitrified Door 3 (Cave Johnson)"
vitrified_door_4_potatos = "Vitrified Door 4 (PotatOS)"
vitrified_door_5_potatos = "Vitrified Door 5 (PotatOS)"
vitrified_door_6_potatos = "Vitrified Door 6 (PotatOS)"
